---
steps:
  # Pull down submodules (aka source)
  - name: gcr.io/cloud-builders/git
    id: Init
    args:
      - "submodule"
      - "update"
      - "--init"
      - "--recursive"
  # Patch
  - name: bash
    id: Patch
    waitFor: ["Init"]
    args:
      - "cp"
      - "actioncable.rb"
      - "src/api/config/initializers/"
  # Build the Docker image
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: Push
    waitFor: ["Patch"]
    args:
      - --dockerfile=src/Dockerfile
      - --context=src/
      - --destination=$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA
      - --destination=$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:latest
      - --cache=true
      - --cache-ttl=48h
  # Set it up in Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Push"]
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
timeout: 1200s
images:
  - "$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _LABELS: gcb-trigger-id=40e1ec8a-84bf-46a1-ba14-22c84c290eab
  _TRIGGER_ID: 40e1ec8a-84bf-46a1-ba14-22c84c290eab
  _DEPLOY_REGION: europe-west1
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: postfacto
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - postfacto
